# This is a workflow to import configurations to IBM Cloud App Configuration service

name: IBM Cloud App Configuration Sync
author: Josephine Eskaline Joyce
description: workflow to import configurations to IBM Cloud App Configuration service

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request are approved
  pull_request:
    branches: [ main ]
    types: [ closed ]
env:
  IBM_CLOUD_API_KEY: cloudkey
  IBM_CLOUD_REGION: au-syd
  IBM_CLOUD_RESOURCE_GROUP: default
  AC_INSTANCE_ID: instanceid
  CONFIG_FILE_NAME: appconfig.json
  GITHUB_REPO: reponame
  GITHUB_PULL_NUMBER: pullnumber

runs:
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Verify if the configuration file is updated
    - name: Check file change
      id: fileChangeMonitor
      run: |
        configurationUpdated=false
        URL="https://api.github.com/repos/${GITHUB_REPO}/pulls/${GITHUB_PULL_NUMBER}/files"
        FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
        echo $FILES
        if echo $FILES | grep -q "$CONFIG_FILE_NAME"; then
          configurationUpdated=true
          echo "Configuration file is updated. "
        fi          
        if [ "$configurationUpdated" == "true" ]
        then
          #Install IBM Cloud CLI 
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false
          ibmcloud plugin install app-configuration
        
          #App Configuration plugin to import configuration
          ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -g "${IBM_CLOUD_RESOURCE_GROUP}" 
          ibmcloud ac init --instance_id "${AC_INSTANCE_ID}"
          ibmcloud ac import --file ./appconfig.json --clean true
        else
          echo "Configuration file is not updated.  No action required"
        fi
      shell: bash
